spring:
  application:
    name: task-platform
  datasource:
    url: jdbc:h2:mem:taskdb
    #dbc:h2:file:~/data/taskdb pour Vraie persistance
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true # Pour voir ta base sur http://localhost:8080/h2-console
  jpa:
    show-sql: true # Pour voir les requetes SQL dans la console
    hibernate:
      ddl-auto: update #Met a jour les tables existantes
