spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_task_db?createDatabaseIfNotExist=true
    username: root
    password: MyStrongP@ssword123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update    # Hibernate cr√©era les tables tout seul !
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#spring:
#  application:
#    name: task-platform
#  datasource:
#
##    url: jdbc:h2:mem:taskdb
##    #dbc:h2:file:~/data/taskdb pour Vraie persistance
##    driverClassName: org.h2.Driver
##    username: sa
##    password:
##  h2:
##    console:
##      enabled: true # Pour voir ta base sur http://localhost:8080/h2-console
#  jpa:
#    show-sql: true # Pour voir les requetes SQL dans la console
#    hibernate:
#      ddl-auto: update #Met a jour les tables existantes
